### ISSUE TITLE
Provide A way to access the markers currently visible on the map

### ISSUE THREAD

**Issue by tyler-r-smith** [kepler-12/vue-simple-maps#2]
We need to be able to access which markers are currently visible on the map.   
Please provide the locations through vuex this allows us to create a list of markers, which is not coupled with map, but rather an agnostic data source.

**Comment by zackkrida** [comment]
@tyler-r-smith okie dokie -- in 0.0.6 the map now has an `onChange` prop which should be a function that receives the visibleMarkers as its only argument. If each map marker has a `locationObject` prop specified, `onChange`'s first argument will be an array of `locationObject`s. Otherwise, it will return the entire vue component of the marker so advanced comparisons/diffing can take place.

So, example implementation...

```vue
    <Map :onChange="doThings">
      <MapMarker :locationObject="location" v-for="location in locations" :position="location.position" :key="location.name">
        <h1>{{ location.name }}</h1>
        <p v-if="location.description">{{ location.description }}</p>
      </MapMarker>
    </Map>

    <ul>
      <li :key="location.name" v-for="location in activeLocations">{{ location.name }}</li>
    </ul>
```

```js
    doThings(activeMarkers) {
      console.log(activeMarkers)
      this.activeLocations = activeMarkers
    },
```
